services:
  - type: web
    name: home-assistant
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TZ
        value: Europe/Athens
    autoDeploy: true
